csv_data_billconn = {
            "BC_MASTER_ID" : 123456,
            "OBJECT_ID" : "123456",
            "SOURCE_ID" : "123456",
            "BILLER_ID" : "billerId",
            "VALID_UNTIL" : "",
            "VALIDATION_ID" : "",
            "BILLER_REFERENCE_NO" : "123456",
            "BILLFETCH_PARAMS" : "",
            "PAYMENT_ID" : "",
            "SOURCE_REF_NO" : "",
            "BBPS_REF_NO" : "txnReferenceId",
            "TXN_DATE_TIME" : "",
            "POSTING_ID" : "",
            "POSTING_DATE" : "postingDate",
            "STATUS" : "csvStatus",      
            "RETRY_COUNT" : 1,              #to bw changed
            "BILLER_RETRY" : "0",
            "CREATED_AT" : "csvStatus",
            "UPDATED_AT" : "csvStatus",
            "CREATED_BY" : "123456",
            "UPDATED_BY" : "123456",
            "BOU_REQ_RESP_ID" : 123456,
            "VALIDATION_DATE" : "",
            "TRACE_ID" : "123456",          #to be changed
            "BILLER_CONNECT_RETRY" : "0",
            "REQ_BD_TIMESTAMP" : "25-AUG-24 07.30.54.000000000 PM",
            "BILL_DATE" : "",
            "BILL_DUE_DATE" : "",
            "BC_ERROR_CODE" : "",
            "BC_ERROR_MESSAGE" : "",
            "VENDOR_RRN" : "",
            "AUTH1" : "",
            "AUTH2" : "",
            "AUTH3" : "123456",
            "AUTH4" : "",
            "VENDOR_REF_ID" : "",
            "SUB_DIV_NAME" : "",
            "BILL_AMOUNT" : "csvStatus", #succ same , fail same as vtbt refund skip 
            "BOU_CONV_FEES" : "0",
            "COU_CONV_FEES" : "0",
            "MODE_OF_PAYMENT" : "csvStatus",
            "BILLER_REQUEST_TYPE" : "",
            "OUID" : ""
        }
print(len(csv_data_billconn))