export const template1 = [
  { value: "ACCOUNT_ID", label:"ACCOUNT_ID"},
  { value: "GSTIN", label: "GSTIN" },
  { value: "REQUEST_TYPE", label: "REQUEST_TYPE" },
  { value: "CUSTOMER_ID", label: "CUSTOMER_ID" },
  { value: "SERVICE_CODE", label: "SERVICE_CODE" },
  { value: "HSN", label:"HSN"},
  { value: "TRANSACTION_CODE", label: "TRANSACTION_CODE" },
  { value: "TRANSACTION_VOLUME", label: "TRANSACTION_VOLUME" },
  { value: "TRANSACTION_VALUE", label: "TRANSACTION_VALUE" },
  { value: "TRANSACTION_PRICED_CHARGE", label: "TRANSACTION_PRICED_CHARGE" },
  { value: "SOURCE_BRANCH", label:"SOURCE_BRANCH"},
  { value: "SOURCE_STATE", label: "SOURCE_STATE" },
  { value: "DESTINATION_BRANCH", label: "DESTINATION_BRANCH" },
  { value: "DESTINATION_STATE", label: "DESTINATION_STATE" },
  { value: "CURRENCY_CODE", label: "CURRENCY_CODE" },
  { value: "CHANNEL", label:"CHANNEL"},
  { value: "SOURCE_SYSTEM", label: "SOURCE_SYSTEM" },
  { value: "CUSTOMER_EXEMPT", label: "CUSTOMER_EXEMPT" },
  { value: "ACCOUNT_EXEMPT", label: "ACCOUNT_EXEMPT" },
  { value: "BRANCH_EXEMPT", label: "BRANCH_EXEMPT" },
  { value: "SERVICE_CHARGE_EXEMPT", label:"SERVICE_CHARGE_EXEMPT"},
  { value: "TRANSACTION_EXEMPT", label: "TRANSACTION_EXEMPT" },
  { value: "RELATED_ENTIY", label: "RELATED_ENTIY" },
  { value: "STANDARD_FEE", label: "STANDARD_FEE" },
  { value: "REVERSAL_TRANSACTION_FLAG", label: "REVERSAL_TRANSACTION_FLAG" },
  { value: "ORIGINAL_TRANSACTION_ID", label:"ORIGINAL_TRANSACTION_ID"},
  { value: "TAX_SPLIT_IN_SOURCE_SYSTEM", label: "TAX_SPLIT_IN_SOURCE_SYSTEM" },
  { value: "CGST_VALUE", label: "CGST_VALUE" },
  { value: "SGST_VALUE", label: "SGST_VALUE" },
  { value: "IGST_VALUE", label: "IGST_VALUE" },
  { value: "UTGST_VALUE", label:"UTGST_VALUE"},
  { value: "GST_STATE", label: "GST_STATE" },
  { value: "GL_ACCOUNT_ID", label: "GL_ACCOUNT_ID" },
  { value: "GST_INVOICE_NUMBER", label: "GST_INVOICE_NUMBER" },
  { value: "USER_C_FIELD_1", label: "USER_C_FIELD_1" },
  { value: "USER_C_FIELD_2", label:"USER_C_FIELD_2"},
  { value: "USER_C_FIELD_3", label: "USER_C_FIELD_3" },
  { value: "USER_C_FIELD_4", label: "USER_C_FIELD_4" },
  { value: "USER_C_FIELD_5", label: "USER_C_FIELD_5" },
  { value: "USER_C_FIELD_6", label: "USER_C_FIELD_6" },
  { value: "USER_C_FIELD_7", label:"USER_C_FIELD_7"},
  { value: "USER_C_FIELD_8", label: "USER_C_FIELD_8" },
  { value: "USER_C_FIELD_9", label: "USER_C_FIELD_9" },
  { value: "USER_C_FIELD_10", label: "USER_C_FIELD_10" },
  { value: "USER_C_FIELD_11", label: "USER_C_FIELD_11" },
  { value: "USER_C_FIELD_12", label:"USER_C_FIELD_12"},
  { value: "USER_C_FIELD_13", label: "USER_C_FIELD_13" },
  { value: "USER_C_FIELD_14", label: "USER_C_FIELD_14" },
  { value: "USER_C_FIELD_15", label: "USER_C_FIELD_15" },
  { value: "USER_N_FIELD_1", label: "USER_N_FIELD_1" },
  { value: "USER_N_FIELD_2", label:"USER_N_FIELD_2"},
  { value: "USER_N_FIELD_3", label: "USER_N_FIELD_3" },
  { value: "USER_N_FIELD_4", label: "USER_N_FIELD_4" },
  { value: "USER_D_FIELD_1", label: "USER_D_FIELD_1" },
  { value: "USER_D_FIELD_2", label:"USER_D_FIELD_2"},
  { value: "USER_D_FIELD_3", label: "USER_D_FIELD_3" },
  { value: "USER_D_FIELD_4", label: "USER_D_FIELD_4" },
  { value: "ACTUAL_USER_ID", label: "ACTUAL_USER_ID" },
  { value: "USER_DEPARTMENT", label:"USER_DEPARTMENT"},
  { value: "REQUEST_DATE", label: "REQUEST_DATE" },
  { value: "REVENUE_ACCOUNT_NUMBER", label: "REVENUE_ACCOUNT_NUMBER" },
  { value: "IGST_ACCOUNT_NUMBER", label: "IGST_ACCOUNT_NUMBER" },
  { value: "CGST_ACCOUNT_NUMBER", label: "CGST_ACCOUNT_NUMBER" },
  { value: "SGST_ACCOUNT_NUMBER", label:"SGST_ACCOUNT_NUMBER"},
  { value: "UTGST_ACCOUNT_NUMBER", label: "UTGST_ACCOUNT_NUMBER" },
  { value: "CGST_CESS_1", label: "CGST_CESS_1" },
  { value: "CGST_CESS_2", label: "CGST_CESS_2" },
  { value: "CGST_CESS_3", label: "CGST_CESS_3" },
  { value: "SGST_CESS_1", label: "SGST_CESS_1" },
  { value: "SGST_CESS_2", label: "SGST_CESS_2" },
  { value: "SGST_CESS_3", label: "SGST_CESS_3" },
  { value: "IGST_CESS_1", label: "IGST_CESS_1" },
  { value: "IGST_CESS_2", label: "IGST_CESS_2" },
  { value: "IGST_CESS_3", label: "IGST_CESS_3" },
  { value: "UTGST_CESS_1", label: "UTGST_CESS_1" },
  { value: "UTGST_CESS_2", label: "UTGST_CESS_2" },
  { value: "UTGST_CESS_3", label: "UTGST_CESS_3" },
  { value: "GST_RATE", label: "GST_RATE" },
  { value: "CGST_RATE", label: "CGST_RATE" },
  { value: "SGST_RATE", label: "SGST_RATE" },
  { value: "IGST_RATE", label: "IGST_RATE" },
  { value: "UTGST_RATE", label: "UTGST_RATE" },
  { value: "CUSTOMER_NAME", label: "CUSTOMER_NAME" },
  { value: "CESS_APPLICABLE", label: "CESS_APPLICABLE" },
  { value: "BUSINESS_UNIT", label: "BUSINESS_UNIT" },
  { value: "GST_R_FIELD_1", label: "GST_R_FIELD_1" },
  { value: "GST_R_FIELD_2", label: "GST_R_FIELD_2" },
  { value: "GST_R_FIELD_3", label: "GST_R_FIELD_3" },
  { value: "GST_R_FIELD_4", label: "GST_R_FIELD_4" },
  { value: "GST_R_FIELD_5", label: "GST_R_FIELD_5" },
  { value: "GST_R_FIELD_6", label: "GST_R_FIELD_6" },
  { value: "GST_R_FIELD_7", label: "GST_R_FIELD_7" },
  { value: "GST_R_FIELD_8", label: "GST_R_FIELD_8" },
  { value: "GST_R_FIELD_9", label: "GST_R_FIELD_9" },
  { value: "GST_R_FIELD_10", label: "GST_R_FIELD_10" },
  { value: "GST_R_FIELD_11", label: "GST_R_FIELD_11" },
  { value: "GST_R_FIELD_12", label: "GST_R_FIELD_12" },
  { value: "GST_R_FIELD_13", label: "GST_R_FIELD_13" },
  { value: "GST_R_FIELD_14", label: "GST_R_FIELD_14" },
  { value: "GST_R_FIELD_15", label: "GST_R_FIELD_15" },
];

export const template2=[
  { value: "AUTH_N", label: "AUTH_N" },
  { value: "AUTH1", label: "AUTH1" },
  { value: "AUTH2", label: "AUTH2" },
  { value: "AUTH3", label: "AUTH3" },
  { value: "AUTH4", label: "AUTH4" },
  { value: "AUTH5", label: "AUTH5" },
  { value: "AUTH6", label: "AUTH6" },
  { value: "AUTH7", label: "AUTH7" },
  { value: "BBPS_STATUS", label: "BBPS_STATUS" },
  { value: "BC_ERROR_CODE", label: "BC_ERROR_CODE" },
  { value: "BC_ERROR_MESSAGE",label:"BC_ERROR_MESSAGE" },
  { value: "BCM _STATUS", label: "BCM_STATUS" },
  { value: "BILLER_CATEGORY", label: "BILLER_CATEGORY" },
  { value: "BILLER_FEE", label: "BILLER_FEE" },
  { value: "BILLER_FEE_CGST", label: "BILLER_FEE_CGST" },
  { value: "BILLER_FEE_IGST", label: "BILLER_FEE_IGST" },
  { value: "BILLER_FEE_SUGST", label: "BILLER_FEE_SUGST" },
  { value: "BILLER_ID", label: "BILLER_ID" },
  { value: "BILLER_OU_COUNT_MONTH", label: "BILLER_OU_COUNT_MONTH" },
  { value: "BILLER_OU_SWITCH_FEE_CGST", label: "BILLER_OU_SWITCH_FEE_CGST" },
  { value: "BILLER_OU_SWITCH_FEE_IGST", label: "BILLER_OU_SWITCH_FEE_IGST" },
  { value: "BILLER_OU_SWITCH_FEE_SUTGST", label: "BILLER_OU_SWITCH_FEE_SUTGST" },
  { value: "BILLER_OU_SWITCHING FEE", label: "BILLER_OU_SWITCHING FEE" },
  { value: "BILLER_OUID", label: "BILLER_OUID" },
  { value: "BILLER_REQUEST_TYPE", label: "BILLER_REQUEST_TYPE" },
  { value: "CLEARING_TIMESTAMP", label: "CLEARING_TIMESTAMP" },
  { value: "CREATED_AT", label: "CREATED_AT" },
  { value: "CUSTOM_REPORT_STATUS", label: "CUSTOM_REPORT_STATUS" },
  { value: "CUSTOMER_CONVENIENCE_FEE", label: "CUSTOMER_CONVENIENCE_FEE" },
  { value: "CUSTOMER_CONVENIENCE_FEE_CGST", label: "CUSTOMER_CONVENIENCE_FEE_CGST" },
  { value: "CUSTOMER_CONVENIENCE_FEE_IGST", label: "CUSTOMER_CONVENIENCE_FEE_" },
  { value: "CUSTOMER_CONVENIENCE_FEE_SUTGST", label: "CUSTOMER_CONVENIENCE_FEE_" },
  { value: "CUSTOMER_OUID", label: "CUSTOMER_OUID" },
  { value: "DEEMED_TYPE", label: "DEEMED_TYPE" },
  { value: "IS_EXCLUDE", label: "IS_EXCLUDE" },
  { value: "IS_TID_REPORT_GENERATED", label: "IS_TID_REPORT_GENERATED" },
  { value: "MODIFIED_AT", label: "MODIFIED_AT" },
  { value: "MSG_ID", label: "MSG_ID" },
  { value: "MTI", label: "MTI" },
  { value: "NET_AMOUNT", label: "NET_AMOUNT" },
  { value: "NPCI_CAS_PROCESSED", label: "NPCI_CAS_PROCESSED" },
  { value: "NPCI_DECLINE", label: "NPCI_DECLINE" },
  { value: "NPCI_FILE_METADATA_ID", label: "NPCI_FILE_METADATA_ID" },
  { value: "NPCI_REMARKS", label: "NPCI_REMARKS" },
  { value: "NPCI_REVERSAL", label: "NPCI_REVERSAL" },
  { value: "NPCI_STATUS", label: "NPCI_STATUS" },
  { value: "OFFUS_PAY", label: "OFFUS_PAY" },
  { value: "OU_LEVEL_REPORT_STATUS", label: "OU_LEVEL_REPORT_STATUS" },
  { value: "PAYMENT_CHANNEL", label: "PAYMENT_CHANNEL" },
  { value: "PAYMENT_MODE", label: "PAYMENT_MODE" },
  { value: "PENALTY_FEE", label: "PENALTY_FEE" },
  { value: "PENALTY_FEE_CGST", label: "PENALTY_FEE_CGST" },
  { value: "PENALTY_FEE_IGST", label: "PENALTY_FEE_IGST" },
  { value: "PENALTY_FEE_SUTGST", label: "PENALTY_FEE" },
  { value: "POSTED_DATE", label: "POSTED_DATE" },
  { value: "REF_ID", label: "REF_ID" },
  { value: "REF_ID_FETCH", label: "REF_ID_FETCH" },
  { value: "RESPONSE_CODE", label: "RESPONSE_CODE" },
  { value: "RETRY_COUNT", label: "RETRY_COUNT" },
  { value: "SETTLEMENT_CYCLE", label: "SETTLEMENT_CYCLE" },
  { value: "SETTLEMENT_CYCLE_DATE", label: "SETTLEMENT_CYCLE_DATE" },
  { value: "SETTLEMENT_CYCLE_ID", label: "SETTLEMENT_CYCLE_ID" },
  { value: "SPLIT_PAY", label: "SPLIT_PAY" },
  { value: "TERMINAL_STATUS", label: "TERMINAL_STATUS" },
  { value: "TID_REPORT_METADATA_ID", label: "TID_REPORT_METADATA_ID" },
  { value: "TXN_AMOUNT", label: "TXN_AMOUNT" },
  { value: "TXN_CURRENCY_CODE", label: "TXN_CURRENCY_CODE" },
  { value: "TXN_DATE", label: "TXN_DATE" },
  { value: "TXN_REFERENCE_ID", label: "TXN_REFERENCE_ID" },
  { value: "TXN_TYPE", label: "TXN_TYPE" }
]

export const dateFormat=[
    { value: "YYYY-MM-DD", label:"YYYY-MM-DD"},
    { value: "DD-MM-YYYY", label:"DD-MM-YYYY"},
    { value: "MM-DD-YYYY", label:"MM-DD-YYYY"},
    { value: "DD/MM/YYYY", label:"DD/MM/YYYY"},
    { value: "MM/DD/YYYY", label:"MM/DD/YYYY"},
    { value: "DD MMM YYYY", label:"DD MMM YYYY"},
    { value: "MMMM DD, YYYY", label:"MMMM DD, YYYY"},
    { value: "YYYY-MM-DDTHH:mm:ssZ", label:"YYYY-MM-DDTHH:mm:ssZ"},
    { value: "YYYY-MM-DD HH:mm:ss", label:"YYYY-MM-DD HH:mm:ss"},
    { value: "DD-MM-YYYY HH:mm", label:"DD-MM-YYYY HH:mm"},
    { value: "MMMM DD, YYYY hh:mm A", label:"MMMM DD, YYYY hh:mm A"},
];

export const dateArray=["ACCOUNT_ID","col2"];
export const amountArray = ["AUTH1","col4"];